import pathlib

root = pathlib.Path(".")
files = sorted(root.rglob("*.zig"), key=lambda p: str(p).lower())
files = [f for f in files if f.name != "unit_tests.zig"]

with open("unit_tests.zig", "w") as f:
    f.write("//! This file is generated by unit_tests_generator.py\n\n")
    f.write("comptime {\n")
    for file in files:
        f.write(f'    _ = @import("{file.as_posix()}");\n')
    f.write("}\n")