//! This file is generated by unit_tests_generator.py

comptime {
    _ = @import("Aof.zig");
    _ = @import("cli.zig");
    _ = @import("cli/Server.zig");
    _ = @import("frames.zig");
    _ = @import("glob.zig");
    _ = @import("main.zig");
    _ = @import("Memory.zig");
    _ = @import("object.zig");
    _ = @import("object/collection.zig");
    _ = @import("object/collection/List.zig");
    _ = @import("object/collection/Map.zig");
    _ = @import("object/scalar.zig");
    _ = @import("object/scalar/Decimal.zig");
    _ = @import("object/scalar/Flag.zig");
    _ = @import("object/scalar/Integer.zig");
    _ = @import("object/scalar/Point.zig");
    _ = @import("object/scalar/String.zig");
    _ = @import("object/scalar/Void.zig");
    _ = @import("object/tagged_ptr.zig");
    _ = @import("Pipeline.zig");
    _ = @import("Query.zig");
    _ = @import("Query/Flags.zig");
    _ = @import("reply.zig");
    _ = @import("RwBuffer.zig");
    _ = @import("Server.zig");
    _ = @import("Server/Listener.zig");
    _ = @import("state_machine.zig");
    _ = @import("Stream.zig");
}
