import pathlib

root = pathlib.Path(__file__).resolve().parent
files = sorted(root.rglob("*.zig"), key=lambda p: str(p).lower())
files = [f for f in files if f.name != "unit_tests.zig"]

with open(root / "unit_tests.zig", "w") as f:
    f.write("//! This file is generated by unit_tests_generator.py\n\n")
    f.write("comptime {\n")
    for file in files:
        path = file.relative_to(root).as_posix()
        f.write(f'    _ = @import("{path}");\n')
    f.write("}\n")